baseURL = 'https://629ef3fc7af95700080527bb--lively-pithivier-93ff92.netlify.app/'
languageCode = 'en-us'
title = 'BOST'
theme = "PaperMod"

[params]
ShowbreadCrumbs = true
ShowReadingTime = true
ShowPostNavLinks = false
ShowShareButtons = false
ShowToc = true
ShowCodeCopyButtons = true
hideFooter = false
defaultTheme = "dark"

  [params.homeInfoParams]
  Title = "Welcome to Leaf Guides"
  Content = "Here you will find lots of useful guides to installing all things for ~free (everything here is strictly for educational purposes only. What you do with this information is up to you)"

  [[params.socialIcons]]
  name = "discord"
  url = "https://discord.gg/NJsDS5YF"

  [[params.socialIcons]]
  name = "reddit"
  url = "https://reddit.com/r/leafguides"

  [[params.socialIcons]]
  name = "github"
  url = "https://www.github.com/leafandJam"
