baseURL = 'https://629ef3fc7af95700080527bb--lively-pithivier-93ff92.netlify.app/'
languageCode = 'en-us'
title = 'Jaq'
theme = "PaperMod"

[params]
ShowbreadCrumbs = true
ShowReadingTime = true
ShowPostNavLinks = false
ShowShareButtons = false
ShowToc = true
ShowCodeCopyButtons = true
hideFooter = false
defaultTheme = "dark"

  [params.homeInfoParams]
  Title = "Welcome to the NEXUS"
  Content = "This will primarily be used as a 'blog' meaning what every i want to post here really. #viewer discretion is advised#"

  [[params.socialIcons]]
  name = "github"
  url = "https://www.github.com/leafandJam"

  [[params.socialIcons]]
  name = "discord"
  url = "https://discord.gg/NJsDS5YF"

  [[params.socialIcons]]
  name = "instagram"
  url = "https://discord.gg/NJsDS5YF"

