baseURL = 'https://jaqs.netlify.app/'
languageCode = 'en-us'
title = 'Jaq'
theme = "PaperMod"

[params]
ShowbreadCrumbs = true
ShowReadingTime = true
ShowPostNavLinks = false
ShowShareButtons = false
ShowToc = true
ShowCodeCopyButtons = true
hideFooter = false
defaultTheme = "dark"

  [params.homeInfoParams]
  Title = "Welcome to the NEXUS"
  Content = "This will primarily be used as a 'blog' meaning what every i want to post here really. (viewer discretion is advised)"

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/JaqShanahan"

  [[params.socialIcons]]
  name = "discord"
  url = "https://discord.gg/KP5d9Yg8"

  [[params.socialIcons]]
  name = "instagram"
  url = "https://www.instagram.com/jaqshanahan/"

[[menu.main]]
identifier = "Categories"
name = "Categories"
url = "/categories/"
weight = 20

[[menu.main]]
identifier = "Archives"
name = "Archives"
url = "/archives/"
weight = 30

[[menu.main]]
identifier = "Search"
name = "Search"
url = "/search/"
weight = 10
