baseURL = 'https://lively-pithivier-93ff92.netlify.app/'
languageCode = 'en-us'
title = 'My New'
theme = theme/hugo-PaperMod

[[menu.main]]
identifier = "categories"
name = "categories"
url = "/categories/"
weight = 10

[[menu.main]]
identifier = "tags"
name = "tags"
url = "/tags/"
weight = 20
